// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBctcw7EdDEFGR-6OOm-wzLvkCkvg9dfvU',
    appId: '1:560362187604:web:40cfc62decdc07b3f276c1',
    messagingSenderId: '560362187604',
    projectId: 'tumaini-web-app-388d0',
    authDomain: 'tumaini-web-app-388d0.firebaseapp.com',
    storageBucket: 'tumaini-web-app-388d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0UNQ9NsIx9HYf_GL6wct-NGAlvEEZui0',
    appId: '1:560362187604:android:59b1798b3828e2cff276c1',
    messagingSenderId: '560362187604',
    projectId: 'tumaini-web-app-388d0',
    storageBucket: 'tumaini-web-app-388d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PPv6AwC6tNyQx6mxjNOez7O-6GgeJj8',
    appId: '1:560362187604:ios:f73701bff78297a7f276c1',
    messagingSenderId: '560362187604',
    projectId: 'tumaini-web-app-388d0',
    storageBucket: 'tumaini-web-app-388d0.firebasestorage.app',
    iosBundleId: 'com.example.tumainiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PPv6AwC6tNyQx6mxjNOez7O-6GgeJj8',
    appId: '1:560362187604:ios:f73701bff78297a7f276c1',
    messagingSenderId: '560362187604',
    projectId: 'tumaini-web-app-388d0',
    storageBucket: 'tumaini-web-app-388d0.firebasestorage.app',
    iosBundleId: 'com.example.tumainiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBctcw7EdDEFGR-6OOm-wzLvkCkvg9dfvU',
    appId: '1:560362187604:web:4ee0b9f94ddd478cf276c1',
    messagingSenderId: '560362187604',
    projectId: 'tumaini-web-app-388d0',
    authDomain: 'tumaini-web-app-388d0.firebaseapp.com',
    storageBucket: 'tumaini-web-app-388d0.firebasestorage.app',
  );
}